api_platform:
    title: Chronox api
    version: 1.0.0
    show_webby: false
    formats:
        json: [ 'application/json' ]
    docs_formats:
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
