api_platform:
    title: Chronox api
    version: 1.0.0
    show_webby: false
    formats:
        json: [ 'application/json' ]
    patch_formats:
        json: [ 'application/json' ]
    docs_formats:
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 20
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
        swagger_ui_extra_configuration:
            persistAuthorization: true
    collection:
        pagination:
            page_parameter_name: page